# Site settings
title: Wild Imagination Press
description: "Creating enchanting children's books to nurture creativity and imagination"
url: "https://wildimaginationpress.com"
baseurl: ""
lang: en
timezone: America/New_York

# SEO settings
tagline: "Where Stories Grow Like Magic"
twitter:
  username: wildimaginpress
  card: summary_large_image
logo: /assets/images/wild-imagination-logo.jpg
social:
  name: Wild Imagination Press
  links:
    - https://x.com/wildimaginpress
    - https://instagram.com/wildimaginationpress

# Author settings
author:
  name: Rebecca Mola
  email: contact@wildimaginationpress.com
  twitter: wildimaginationpress

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# Collections
collections:
  books:
    output: true
    permalink: /:collection/:name/

# Sitemap configuration
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      sitemap:
        priority: 0.7
        changefreq: weekly
  - scope:
      path: ""
      type: "books"
    values:
      sitemap:
        priority: 0.9
        changefreq: monthly
  - scope:
      path: "index.html"
    values:
      sitemap:
        priority: 1.0
        changefreq: weekly

# Exclude files from Jekyll build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - WARP.md
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .git/
  - .bundle/
  - tmp/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/

# SEO settings
google_analytics: G-F2V6B1H630
logo: /assets/images/wild-imagination-logo.jpg

# Social settings
social:
  instagram: wildimaginationpress
  twitter: wildimaginpress

# Navigation
nav_links:
  - name: Home
    url: /
  - name: Books
    url: /books/
  - name: About Author
    url: /#author
  - name: Contact
    url: /#contact

# Theme settings
theme_color: "#27ae60"
accent_color: "#74b9ff"